version: "2"

services:
  tweek-backoffice:
    image: node:6.10.0-slim
    volumes: 
      - .:/opt/app
    ports:
      - 8080:8080
      - 8081:8081
    working_dir: /opt/app
    environment: 
      - NODE_ENV=development
      - PORT=8080
      - AUTO_RELOAD=hot
    command: ["npm", "start"]
      
    