# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/authoring"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Asia/Jerusalem
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/services/editor"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Asia/Jerusalem
    target-branch: "master"
  - package-ecosystem: "nuget"
    directory: "/services/publishing/Tweek.Publishing.Service"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Asia/Jerusalem
    target-branch: "master"
  - package-ecosystem: "nuget"
    directory: "/services/api/Tweek.ApiService"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Asia/Jerusalem
    target-branch: "master"
  - package-ecosystem: "gomod"
    directory: "/services/gateway"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Asia/Jerusalem
    target-branch: "master"
