version: 0.0.{build}
configuration: Release
hosts:
  tweek-couchbase-1.dyurid5y0qhuvon1hlx3z33oye.bx.internal.cloudapp.net: 40.117.43.1
  tweek-couchbase-2.dyurid5y0qhuvon1hlx3z33oye.bx.internal.cloudapp.net: 40.80.150.52
  tweek-couchbase-3.dyurid5y0qhuvon1hlx3z33oye.bx.internal.cloudapp.net: 40.80.148.200
before_build:
- cmd: nuget restore -verbosity quiet
build:
  verbosity: quiet
artifacts:
- path: Tweek.ApiService
  name: Tweek.ApiService
  type: WebDeployPackage
before_test:
- ps: .\beforeTests.ps1
test:
  assemblies:
    - '**\*tests.dll'
after_test:
- ps: .\afterTests.ps1
skip_commits:
  files:
    - BackOffice/*
    - .travis.yml
    - circle.yml