version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1.2-sdk
        environment:
          - DOTNET_CLI_TELEMETRY_OUTPUT=1
      
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Build nugets
          command: |
            export Version=0.0.$CIRCLE_BUILD_NUM
            mkdir /nugets && \
            cd addons/Context/ContextDriversIntegrationTests/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - deploy:
          name: Push nugets
          command: |
            export Version=0.0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [[ $(git diff-tree --no-commit-id --name-only -r HEAD | grep -c "addons/Context") != "0" ]]; then
                dotnet nuget push /nugets/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_APIKEY -n -d
              else
                echo "Code didn't change will not push the nuget"
              fi
            else
              echo "Will not push nuget from non-master branch"
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build