version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    working_directory: /BackOffice

    docker:
      - image: node:6.10.1

    environment:
      NODE_ENV: development
      YARN_VERSION: 0.17.8
      PATH: "${PATH}:${HOME}/.yarn/bin:/usr/sbin:/sbin"
    
    steps:
      - run: |
        echo $TWEEK_API_HOSTNAME && echo ${TWEEK_API_HOSTNAME}
        wget --tries 20 --timeout=15 --read-timeout=20 --waitretry=30 --retry-connrefused ${TWEEK_API_HOSTNAME}
      
      - restore_cache:
        kes:
          - docker-cache-{{ .Branch }}
          - docker-cache-master
          - docker-cache-

      - run: |
        if [[ -e ~/docker/tweek-images.tar ]]; then
          docker load -i ~/docker/tweek-images.tar
          echo "found cached images"
        else
          echo "cached images were not found"
        fi
        docker images
        docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
        docker-compose pull
        docker-compose build
        docker-compose up -d
        mkdir -p ~/docker
        docker save soluto/tweek-api:latest soluto/tweek-management:latest backoffice_tweek-backoffice > ~/docker/tweek-images.tar

      - save_cache:
          key: docker-cache-{{ .Branch }}
          paths:
            - ~/docker
      
      - restore_cache:
        kes:
          - yarn-cache-{{ .Branch }}
          - yarn-cache-master
          - yarn-cache-

      - run: yarn

      - save_cache:
          key: yarn-cache-{{ .Branch }}
          paths:
            - ~/.yarn-cache

      - run: |
        wget --tries 20 --timeout=15 --read-timeout=20 --waitretry=30 --retry-connrefused 'http://localhost:4000/keys'
        wget --tries 20 --timeout=15 --read-timeout=20 --waitretry=30 --retry-connrefused 'localhost:1111/status'
        yarn test:unit && yarn test:e2e

      - deploy: |
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
          docker tag backoffice_tweek-backoffice:latest soluto/tweek-back-office
          docker push soluto/tweek-back-office
        else 
          echo "not deploying on non master branches"
        fi
