version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1.2-sdk
        environment:
          - DOTNET_CLI_TELEMETRY_OUTPUT=1
      - image: redis:alpine
      
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Build integration tests nuget
          command: |
            mkdir -p /nugets
            export Version=0.0.$CIRCLE_BUILD_NUM
            cd addons/Context/ContextDriversIntegrationTests/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Build redis driver nuget
          command: |
            mkdir -p /nugets
            export Version=0.0.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Redis/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Build couchbase driver nuget
          command: |
            mkdir -p /nugets
            export Version=0.0.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Couchbase/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Build Api Addons nuget
          command: |
            mkdir -p /nugets
            export Version=0.0.$CIRCLE_BUILD_NUM
            cd core/Tweek.ApiService.Addons/ && \
            dotnet restore && \
            dotnet build -c release -o /nugets

      - run:
          name: Test redis driver
          command: |
            mkdir -p /nugets
            export Version=0.0.$CIRCLE_BUILD_NUM
            cd addons/Context/Tweek.Drivers.Redis.ContextIntegrationTests/ && \
            dotnet restore && \
            REDIS_TEST_CONNECTION="127.0.0.1:6379" dotnet test

      - deploy:
          name: Push nugets
          command: |
            export Version=0.0.$CIRCLE_BUILD_NUM
            #if [ "${CIRCLE_BRANCH}" == "master" ]; then
            #  if [[ $(git diff-tree --no-commit-id --name-only -r HEAD | grep -cP "addons\/Context|core\/Tweek.ApiService.Addons") != "0" ]]; then
                find /nugets -name "*.nupkg" | xargs -n1 dotnet nuget push -s nuget.org -k $NUGET_APIKEY -n -d
            #  else
            #    echo "Code didn't change will not push the nuget"
            #  fi
            #else
            #  echo "Will not push nuget from non-master branch"
            #fi

workflows:
  version: 2
  build_test_and_push:
    jobs:
      - build
