version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1.2-sdk
      environment:
        - DOTNET_CLI_TELEMETRY_OUTPUT=1
        - VersionSuffix=$CIRCLE_BUILD_NUM
      
    working_directory: /src
    steps:
      - checkout
      - run:
        name: Build nugets
        command: |
          mkdir /nugets && \
          cd addons/Context/ContextDriversIntegrationTests/ && \
          dotnet restore && \
          dotnet build -c release -o /nugets

      - deploy:
        name: Push nugets
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            dotnet nuget push /nugets/*.nupkg -s nuget.org -k $NUGET_APIKEY
          else
            echo "Will not push nuget from non-master branch"
          fi
