version: 2
jobs:
  build:
    branches:
      ignore:
        - docs
        - gh-pages

    working_directory: ~/tweek

    environment:
      NODE_ENV: development
 
    docker:
      - image: node:6.10.1
    
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            curl -L -o /usr/bin/docker-compose "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)"
            chmod +x /usr/bin/docker-compose

      - run: 
          name: Build tweek-backoffice
          working_directory: ~/tweek/deployments/dev
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.circleci.yml pull selenium tweek-management tweek-api
            docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.circleci.yml build tweek-git backoffice-e2e
            docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.circleci.yml build tweek-backoffice

      - run:
          name: Run tweek-backoffice
          working_directory: ~/tweek/deployments/dev
          command: docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.circleci.yml up -d tweek-backoffice
      
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "services/editor/yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-master
            - yarn-cache-

      - run:
          name: yarn install
          working_directory: ~/tweek/services/editor
          command: yarn --cache-folder "/.yarn-cache"

      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "services/editor/yarn.lock" }}
          paths:
            - ~/tweek/services/editor.yarn-cache

      - run: 
          name: Run unit tests
          working_directory: ~/tweek/services/editor
          command: yarn test:unit
            
      - run:
          name: Prepare for e2e tests
          working_directory: ~/tweek/deployments/dev
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.circleci.yml run -d selenium
            docker run --network=dev_default node:6.10.1-slim wget --tries 20 --timeout=15 --read-timeout=20 --waitretry=30 --retry-connrefused http://tweek-api/status
            

      - run:
          name: Run e2e tests
          working_directory: ~/tweek/deployments/dev
          command: docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.circleci.yml run backoffice-e2e

      - deploy: 
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
              docker push soluto/tweek-back-office
            else 
              echo "not deploying on non master branches"
            fi
