version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    working_directory: /BackOffice

    environment:
      NODE_ENV: development
      YARN_VERSION: 0.17.8

    docker:
      - image: node:6.10.1
    
    steps:
      - run: |
          echo "starting!"
          uname -a
