version: '2'

services:
  tweek-management:
    image: soluto/tweek-management
    build:
      context: ../../services/management
      dockerfile: Dockerfile
    environment:
      - VALIDATION_URL=http://tweek-api/validation
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  tweek-api:
    image: soluto/tweek-api
    build:
      context: ../../
      dockerfile: TweekApiDockerfile
    depends_on:
      - tweek-management
      - tweek-redis
    environment:
      - Rules__Management__Url=http://tweek-management:3000
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  tweek-redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "4005:6379"

  tweek-editor:
    image: soluto/tweek-back-office
    build: ../../services/editor
    depends_on: 
      - tweek-api
    environment:
      - TWEEK_API_HOSTNAME=http://tweek-api
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
