version: '2'

services:
  keys:
    build: "../../services/git-service/ssh"

  tweek-git:
    volumes_from: 
      - keys
    environment:
      - PUBLIC_KEY_PATH=/gitkeys/tweekgit.pub
    volumes: []

  tweek-management:
    volumes_from: 
      - keys
    environment: 
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit
      - GIT_PUBLIC_KEY_PATH=/gitkeys/tweekgit.pub
    volumes: []

  tweek-editor:
    volumes_from: 
      - keys
    environment: 
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit
      - GIT_PUBLIC_KEY_PATH=/gitkeys/tweekgit.pub
    volumes: []

  tweek-api:
    volumes_from: 
      - keys
    environment: 
      - PUBLIC_KEY_PATH=/gitkeys/tweekgit_public.pfx
    volumes: []
