version: '3.4'

services:
  publishing:
    build:
      args:
        target: Release

    environment:
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/tests

  editor:
    environment:
      - CONTINUOUS_UPDATER_INTERVAL=500

  authoring:
    environment:
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    build:
      args:
        target: Release
    depends_on:
      - publishing
    environment:
      - CorsPolicies__Keys__Origins=http://editor,http://gateway,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
      - Context__Validation__ErrorPolicy=throw

  gateway:
    environment:
      - CONFIGOR_ENV=test

  oidc-server-mock:
    environment:
      - REDIRECT_URIS=http://gateway/auth-result/oidc

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    shm_size: 2g
    volumes:
      - ../../e2e/ui:/src
      - /src/node_modules
    depends_on:
      - gateway
      - editor
    environment:
      - GATEWAY_URL=http://gateway
      - EDITOR_URL=http://gateway
      - AUTH_DIGEST_CREDENTIALS=user:pwd
    command: ["-q", "-S", "-s", "/src/screenshots", "-c", "4", "chromium --headless --window-size='1280,720' --no-sandbox", "/src/spec" ]

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    volumes:
      - ../../e2e/integration:/opt/app
      - /opt/app/node_modules
    depends_on: 
      - gateway
    environment:
      - GATEWAY_URL=http://gateway
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY_PATH=/run/secrets/minio_access_key
      - MINIO_SECRET_KEY_PATH=/run/secrets/minio_secret_key
      - MINIO_BUCKET=tweek
    secrets:
      - minio_access_key
      - minio_secret_key

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTest.Dockerfile
    container_name: smoke-tests
    depends_on:
      - api
      - publishing
      - gateway
    environment:
      - TWEEK_API_URL=http://api/
    links:
      - gateway:api

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key
