version: '3.4'

services:
  git:
    image: soluto/tweek-bare-repo
    build: ../../services/git-service/BareRepository
    ports: 
      - "4001:22"
    environment:
      - PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
    secrets:
      - tweek_ssh_public_key
  
  publishing:
    image: soluto/tweek-publishing
    build: 
      args: 
        target: Debug
    ports:
      - "4009:22"
      - "4010:80"
    depends_on:
      - git
      - minio
      - nats
    environment:
      - GIT_PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - GIT_SERVER_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/repo
      - MINIO__Endpoint=minio:9000
      - MINIO__AccessKey=AKIAIOSFODNN7EXAMPLE
      - MINIO__SecretKeyPath=/run/secrets/minio_secret_key
      - NATS__Endpoint=nats://nats:4222
    secrets:
      - tweek_ssh_public_key
      - tweek_ssh_private_key
      - minio_secret_key
 
  api:
    ports:
      - "4003:80"
    depends_on:
      - redis
      - minio
      - nats
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PUBLIC_KEY_PATH=/run/secrets/tweek_pfx_public_key
      - Redis__ConnectionString=redis:6379
      - Rules__Minio__Endpoint=minio:9000
      - Rules__Minio__AccessKeyPath=/run/secrets/minio_access_key
      - Rules__Minio__SecretKeyPath=/run/secrets/minio_secret_key
      - Rules__Nats__Endpoint=nats://nats:4222
      - UseAddon__Rules=MinioRules
      - RulesetVersionProvider=NatsVersionProvider
    secrets:
      - tweek_pfx_public_key
      - minio_access_key
      - minio_secret_key

  editor:
    ports:
      - "4004:3000"
    volumes: 
      - ../../services/editor/vapid:/opt/vapid
    environment:
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key

  authoring:
    depends_on:
      - publishing
    ports:
      - "5859:5858"
      - "4005:3000"
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@publishing/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key
      - tweek_ssh_public_key
    command:
      - yarn 
      - start:debug
    labels:
      - "traefik.port=3000"

  redis:
    image: redis:4.0.2-alpine
    expose:
      - "6379"
    ports:
      - "4006:6379"
  
  minio:
    image: minio/minio
    ports:
      - "4007:9000"
    command: server /data
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key

  nats:
    image: nats:1.0.4-linux
    ports:
      - "4008:8222"
      - "4222:4222"

  gateway:
    ports:
      - "80:80"
      - "4099:3000"
    environment:
      - TWEEKGATEWAY_SECURITY_CORS_ENABLED=true
      - TWEEKGATEWAY_SECURITY_CORS_MAXAGE=60
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDORIGINS=null
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDMETHODS=['GET','POST','PUT','PATCH','DELETE']
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDHEADERS=null
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWCREDENTIALS=true
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOENDPOINT=minio:9000
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOBUCKETNAME=tweek-casbin-policies
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOACCESSKEY=AKIAIOSFODNN7EXAMPLE
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECRETKEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECURE=false
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOPOLICYOBJECTNAME=policy.csv
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSENDPOINT=nats://nats:4222
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSSUBJECT=casbin-policy-subject
      - TWEEKGATEWAY_SECURITY_TWEEKSECRETKEYPATH=/run/secrets/tweek_ssh_private_key
      - CONFIG_FILE_PATH=/config/gateway.json
    secrets:
      - tweek_ssh_private_key

  casbin-minio-loader:
    image: casbin-minio-loader
    build: ../../tools/casbin-minio-loader
    depends_on:
      - minio
      - nats
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_BUCKET=tweek-casbin-policies
      - MINIO_SECURE=false
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - NATS_ENDPOINT=nats://nats:4222
      - NATS_SUBJECT=casbin-policy-subject


secrets:
  tweek_ssh_public_key:
    file: ./ssh/tweekgit.pub
  tweek_pfx_public_key:
    file: ./ssh/tweekgit_public.pfx
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key