version: '3.1'

services:
  management:
    image: soluto/tweek-management
    build: ../../services/management
    environment:
      - VALIDATION_URL=http://api/validation

  api:
    image: soluto/tweek-api
    depends_on:
      - management
    build:
      context: ../../
      dockerfile: TweekApiDockerfile

  authoring:
    image: soluto/tweek-authoring
    build: ../../services/authoring

  editor:
    image: soluto/tweek-editor
    build: ../../services/editor
    depends_on: 
      - api
      - authoring
