version: '3.1'

services:
  git:
    image: soluto/tweek-bare-repo
    build: ../../services/git-service/BareRepository
    ports: 
      - "4001:22"
    environment:
      - PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - TWEEK_MANAGEMENT_URL=http://management:3000
    secrets:
      - tweek_ssh_public_key
 
  management:
    depends_on:
      - git
    expose:
      - "5858"
    ports:
      - "5858:5858"
      - "4002:3000"
    entrypoint:
      - node
      - --inspect=5858
      - ./src/server.js
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@git/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_public_key
      - tweek_ssh_private_key
    labels:
      - "traefik.port=3000"
  
  api:
    ports:
      - "4003:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PUBLIC_KEY_PATH=/run/secrets/tweek_pfx_public_key
      - ContextProvider=redis
      - Redis__ConnectionString=redis:6379
      - Addons__Redis__className=Tweek.Drivers.Redis.RedisServiceAddon
      - Addons__Redis__assemblyName=Tweek.Drivers.Redis
    secrets:
      - tweek_pfx_public_key

  editor:
    ports:
      - "4004:3000"
    volumes: 
      - ../../services/editor/vapid:/opt/vapid
    environment:
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key

  authoring:
    depends_on:
      - git
    ports:
      - "5859:5858"
      - "4005:3000"
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@git/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key
      - tweek_ssh_public_key
    entrypoint:
      - node
      - --inspect=5858
      - ./src/server.js
    labels:
      - "traefik.port=3000"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "4006:6379"
  
  gateway:
    image: traefik:1.3.2
    ports:
      - "${TWEEK_GATEWAY_PORT:-81}:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    command: --web --docker --docker.domain=tweek.localtest.me --logLevel=DEBUG

secrets:
  tweek_ssh_public_key:
    file: ../../services/git-service/ssh/tweekgit.pub
  tweek_pfx_public_key:
    file: ../../services/git-service/ssh/tweekgit_public.pfx
  tweek_ssh_private_key:
    file: ../../services/git-service/ssh/tweekgit
