version: '3.1'

services:
  api:
    image: soluto/tweek-api:dev
    build:
      context: ../../services/api/Tweek.ApiService.NetCore
      dockerfile: Dockerfile
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ../../services/api/Tweek.ApiService.NetCore:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  redis:
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  gateway:
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  management:
    build: {
    }
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  editor:
    build: {}
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  git:
    build: {}
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  authoring:
    build: {}
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
