version: '2'

services:
  tweek-management:
    image: soluto/tweek-management
    build:
      context: ../../services/management
      dockerfile: Dockerfile
    environment:
      - VALIDATION_URL=http://tweek.apiservice.netcore/validation
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  tweek.apiservice.netcore:
    image: soluto/tweek-api
    build:
      context: ../../services/api/Tweek.ApiService.NetCore
      dockerfile: Dockerfile
    depends_on:
      - tweek-management
    environment:
      - Rules__Management__Url=http://tweek-management:3000
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
     
  tweek-editor:
    image: soluto/tweek-back-office
    build: ../../services/editor
    depends_on: 
      - tweek.apiservice.netcore
    environment:
      - TWEEK_API_HOSTNAME=http://tweek.apiservice.netcore
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
