version: "2"

services:
  tweek-git:
    build: ../../services/git-service/BareRepository/.
    container_name: tweek-git
    ports: 
      - "40:22"
    environment:
      - PUBLIC_KEY_PATH=/tweek/key.pub
      - TWEEK_MANAGEMENT_URL=http://tweek-management:3000
    volumes:
      -  ../../services/git-service/ssh/tweekgit.pub:/tweek/key.pub

  tweek-management:
    image: soluto/tweek-management
    build: ../../services/management
    container_name: tweek-management
    depends_on:
      - tweek-git
    volumes:
      - ../../services/git-service/ssh:/keys
    ports:
      - "41:3000"
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@tweek-git/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/keys/tweekgit.pub
      - GIT_PRIVATE_KEY_PATH=/keys/tweekgit
      - VALIDATION_URL=http://tweek-api/validation

  tweek-api:
    image: soluto/tweek-api
    build: "../../services/api/Tweek.ApiService.NetCore"
    container_name: tweek-api
    depends_on:
      - tweek-management
    ports:
      - "42:80"
    environment:
      - RulesBlob.Url=http://tweek-management:3000/ruleset/latest

  tweek-backoffice:
    build: ../../services/editor/
    container_name: tweek-backoffice
    depends_on: 
      - tweek-api
      - tweek-git
    ports:
      - "43:3000"
    volumes: 
      - ../GitService/ssh:/keys
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@tweek-git/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/keys/tweekgit.pub
      - GIT_PRIVATE_KEY_PATH=/keys/tweekgit
      - TWEEK_API_HOSTNAME=http://tweek-api
