version: '3.4'

services:
  publishing:
    environment: 
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/tests

  editor:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500
      - REQUIRE_AUTH=true
      - TWEEK_AUTH_SCHEMES=httpDigest
      - AUTH_DIGEST_CREDENTIALS=user:pwd

  authoring:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    depends_on:
      - publishing
    environment:
      - CorsPolicies__Keys__Origins=http://editor:3000,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
  
  selenium:
    image: selenium/standalone-chrome:3.8.1
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - gateway:api
      - gateway:authoring

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    links:
      - selenium
      - gateway:api
      - gateway:authoring      
    depends_on: 
      - selenium
      - publishing
      - editor
      - gateway
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000/
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - AUTH_DIGEST_CREDENTIALS=user:pwd
    secrets:
      - tweek_ssh_private_key      

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    depends_on:
      - gateway
      - publishing
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - GATEWAY_URL=http://gateway
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY_PATH=/run/secrets/minio_access_key
      - MINIO_SECRET_KEY_PATH=/run/secrets/minio_secret_key
      - MINIO_BUCKET=tweek
    secrets:
      - tweek_ssh_private_key
      - minio_access_key
      - minio_secret_key
    links:
      - gateway:api
      - gateway:authoring

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTestDockerfile
    container_name: smoke-tests
    depends_on: 
      - gateway
      - publishing
    environment: 
      - TWEEK_API_URL=http://api/
    links:
      - gateway:api

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key
