version: '2'

services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium

  backoffice-e2e:
    build: ../../e2e
    container_name: e2e
    links:
      - selenium
    depends_on: 
      - selenium
    volumes: 
      - ../../services/git-service/ssh:/keys
    environment:
      - EDITOR_URL=http://tweek-editor:3000/
      - TWEEK_API_URL=http://tweek-api/
      - GIT_PRIVATE_KEY_PATH=/keys/tweekgit

  tweek-management:
    environment: 
      - GIT_URL=ssh://git@tweek-git/tweek/tests

  tweek-editor:
    environment: 
      - GIT_URL=ssh://git@tweek-git/tweek/tests
      - CONTINUOUS_UPDATER_INTERVAL=500

  tweek-api:
    environment:
      - Rules__Management__SampleIntervalInMs=500
      - CorsPolicies__Keys__Origins=http://tweek-editor:3000,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
