version: '3.4'

services:
  api:
    image: soluto/tweek-api
    build:
      context: ../../
      dockerfile: TweekApi.Dockerfile

  authoring:
    image: soluto/tweek-authoring
    build:
      context: ../../services/authoring
    depends_on:
      - publishing

  editor:
    image: soluto/tweek-editor
    build:
      context: ../../services/editor
    depends_on:
      - gateway

  gateway:
    image: soluto/tweek-gateway
    build: 
      context: ../../services/gateway
    depends_on:
      - publishing
      - api
      - authoring

  publishing:
    image: soluto/tweek-publishing
    build: 
      context: ../../services/publishing

