version: '2'

services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium

  backoffice-e2e:
    build: ../../e2e
    container_name: e2e
    links:
      - selenium
    depends_on: 
      - selenium
    environment:
      - BACKOFFICE_URL=http://tweek-editor:3000/

  tweek-management:
    environment: 
      - GIT_URL=ssh://git@tweek-git/tweek/tests

  tweek-editor:
    environment: 
      - GIT_URL=ssh://git@tweek-git/tweek/tests
