version: '3.4'

services:
  publishing:
    build: 
      args: 
        target: Release

    environment: 
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/tests

  editor:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  authoring:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    build: 
      args: 
        target: Release
    depends_on:
      - publishing
    environment:
      - CorsPolicies__Keys__Origins=http://editor,http://gateway,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
      - Context__Validation__ErrorPolicy=throw
      
  gateway:
    environment:
      - CONFIGOR_ENV=test    

  oidc-server-mock:
    container_name: oidc-server-mock 
    image: soluto/oidc-server-mock   
    ports:
      - "8081:80"
    environment: 
      - REDIRECT_URIS=http://gateway/auth-result/oidc
  
  
  selenium:
    image: selenium/standalone-chrome-debug:3.8.1
    container_name: selenium
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    links:
      - gateway:api
      - gateway:authoring

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    links:
      - selenium
      - gateway:api
      - gateway:authoring      
    depends_on: 
      - selenium
      - api
      - authoring
      - publishing
      - editor
      - gateway
    environment:
      - GATEWAY_URL=http://gateway/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - AUTH_DIGEST_CREDENTIALS=user:pwd
    secrets:
      - tweek_ssh_private_key

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    depends_on: 
      - api
      - authoring
      - gateway
      - publishing
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring
      - GATEWAY_URL=http://gateway
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY_PATH=/run/secrets/minio_access_key
      - MINIO_SECRET_KEY_PATH=/run/secrets/minio_secret_key
      - MINIO_BUCKET=tweek
    secrets:
      - tweek_ssh_private_key
      - minio_access_key
      - minio_secret_key
    links:
      - gateway:api
      - gateway:authoring

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTest.Dockerfile
    container_name: smoke-tests
    depends_on: 
      - api
      - publishing
      - gateway
    environment: 
      - TWEEK_API_URL=http://api/
    links:
      - gateway:api

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key
