version: '3.4'

services:
  git:
    image: soluto/tweek-bare-repo
    build: ../../services/git-service/BareRepository
    ports:
      - "4001:22"
    environment:
      - PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
    secrets:
      - tweek_ssh_public_key

  publishing:
    image: soluto/tweek-publishing
    build:
      args:
        target: Debug
    ports:
      - "4009:22"
      - "4010:80"
    depends_on:
      - git
      - minio
      - nats
    environment:
      - GIT_PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - GIT_SERVER_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/repo
      - MINIO__Endpoint=minio:9000
      - MINIO__AccessKey=AKIAIOSFODNN7EXAMPLE
      - MINIO__SecretKeyPath=/run/secrets/minio_secret_key
      - NATS__Endpoint=nats://nats:4222
    secrets:
      - tweek_ssh_public_key
      - tweek_ssh_private_key
      - minio_secret_key

  api:
    build:
      args:
        target: Debug
    ports:
      - "4003:80"
    depends_on:
      - redis
      - minio
      - nats
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PUBLIC_KEY_PATH=/run/secrets/tweek_pfx_public_key
      - Redis__ConnectionString=redis:6379
      - Rules__Minio__Endpoint=minio:9000
      - Rules__Minio__Bucket=tweek
      - Rules__Minio__AccessKeyPath=/run/secrets/minio_access_key
      - Rules__Minio__SecretKeyPath=/run/secrets/minio_secret_key
      - Rules__Nats__Endpoint=nats://nats:4222
      - UseAddon__Rules=MinioRules
      - RulesetVersionProvider=NatsVersionProvider
    secrets:
      - tweek_pfx_public_key
      - minio_access_key
      - minio_secret_key

  editor:
    ports:
      - "4004:3000"

  authoring:
    depends_on:
      - publishing
    ports:
      - "5859:5858"
      - "4005:3000"
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@publishing/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/run/secrets/tweek_ssh_public_key
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key
      - tweek_ssh_public_key
    command:
      - yarn
      - start:debug
    labels:
      - "traefik.port=3000"

  redis:
    image: redis:4.0.2-alpine
    expose:
      - "6379"
    ports:
      - "4006:6379"

  minio:
    image: minio/minio
    ports:
      - "4007:9000"
    command: server /data
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key

  nats:
    image: nats:1.0.4-linux
    ports:
      - "4008:8222"
      - "4222:4222"

  oidc-server-mock:
    container_name: oidc-server-mock
    image: soluto/oidc-server-mock:0.1.0
    ports:
      - "8082:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "ClientId": "tweek-openid-mock-client",
            "Description": "Tweek OIDC Mock",
            "AllowedGrantTypes": [
                "implicit"
            ],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": [
                "http://localhost:8081/auth-result/oidc"
            ],
            "AllowedScopes": [
                "openid",
                "profile",
                "email"
            ],
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"user",
            "Username":"user",
            "Password":"pwd"
          }
        ]

  gateway:
    ports:
      - "8081:80"
    depends_on:
      - minio
      - nats
      - oidc-server-mock
    environment:
      - TWEEKGATEWAY_SECURITY_CORS_ENABLED=true
      - TWEEKGATEWAY_SECURITY_CORS_MAXAGE=60
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDORIGINS=['*']
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDMETHODS=['GET','POST','PUT','PATCH','DELETE']
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDHEADERS=['*']
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOENDPOINT=minio:9000
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOBUCKETNAME=tweek
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOACCESSKEY=AKIAIOSFODNN7EXAMPLE
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECRETKEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECURE=false
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSENDPOINT=nats://nats:4222
      - TWEEKGATEWAY_SECURITY_TWEEKSECRETKEY_PATH=/run/secrets/tweek_ssh_private_key
      - TWEEKGATEWAY_SECURITY_AUTH_BASICAUTH_REDIRECTURLS=['http://localhost:8081', 'http://localhost:3000']
      - TWEEKGATEWAY_CONFIGFILEPATH=/config/gateway.json
    volumes:
      - ./gateway/config:/config
    secrets:
      - tweek_ssh_private_key

secrets:
  tweek_ssh_public_key:
    file: ./ssh/tweekgit.pub
  tweek_pfx_public_key:
    file: ./ssh/tweekgit_public.pfx
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key
