version: '3.4'

services:
  publishing:
    build: 
      args: 
        target: Release

    environment: 
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/tests

  editor:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500
      - REQUIRE_AUTH=true
      - TWEEK_AUTH_SCHEMES=httpDigest
      - AUTH_DIGEST_CREDENTIALS=user:pwd

  authoring:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    build: 
      args: 
        target: Release
    depends_on:
      - publishing
    environment:
      - CorsPolicies__Keys__Origins=http://editor:3000,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
      - Context__Validation__ErrorPolicy=throw
  
  selenium:
    image: selenium/standalone-chrome:3.13.0
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    links:
      - selenium
    depends_on: 
      - selenium
      - api
      - authoring
      - publishing
      - editor
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000/
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - AUTH_DIGEST_CREDENTIALS=user:pwd
    secrets:
      - tweek_ssh_private_key

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    depends_on: 
      - api
      - authoring
      - publishing
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTestDockerfile
    container_name: smoke-tests
    depends_on: 
      - api
      - publishing
    environment: 
      - TWEEK_API_URL=http://api/

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
