version: '3.4'

services:
  publishing:
    build: 
      args: 
        target: Release

    environment: 
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/tests

  editor:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  authoring:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    build: 
      args: 
        target: Release
    depends_on:
      - publishing
    environment:
      - CorsPolicies__Keys__Origins=http://editor:3000,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
      
  gateway:
    depends_on:       
      - minio
      - nats
      - oidc-server-mock
    environment:
      - CONFIGOR_ENV=test

  oidc-server-mock:
    container_name: oidc-server-mock 
    image: soluto/oidc-server-mock   
    ports:
      - "4011:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - CLIENT_ID=tweek-openid-mock-client
      - REDIRECT_URIS=http://editor:3000/auth/oidc,http://localhost:3000/auth/oidc,http://localhost:4004/auth/oidc
      - TEST_USER={"SubjectId":"00000000-0000-0000-0000-000000000000","Username":"User1","Password":"pwd"}
  
  selenium:
    image: selenium/standalone-chrome-debug:3.8.1
    container_name: selenium
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    links:
      - gateway:api
      - gateway:authoring

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    links:
      - selenium
      - gateway:api
      - gateway:authoring      
    depends_on: 
      - selenium
      - publishing
      - editor
      - gateway
    environment:
      - GATEWAY_URL=http://gateway/
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000/
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - AUTH_DIGEST_CREDENTIALS=user:pwd
    secrets:
      - tweek_ssh_private_key      

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    depends_on:
      - gateway
      - publishing
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - GATEWAY_URL=http://gateway
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY_PATH=/run/secrets/minio_access_key
      - MINIO_SECRET_KEY_PATH=/run/secrets/minio_secret_key
      - MINIO_BUCKET=tweek
    secrets:
      - tweek_ssh_private_key
      - minio_access_key
      - minio_secret_key
    links:
      - gateway:api
      - gateway:authoring

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTest.Dockerfile
    container_name: smoke-tests
    depends_on: 
      - gateway
      - publishing
    environment: 
      - TWEEK_API_URL=http://api/
    links:
      - gateway:api

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key
