version: '3.4'

services:
  publishing:
    build:
      args:
        target: Release

  authoring:
    environment:
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    build:
      args:
        target: Release
    depends_on:
      - publishing

  oidc-server-mock:
    container_name: oidc-server-mock
    image: soluto/oidc-server-mock:0.1.0
    ports:
      - "8081:80"
    environment:
      [
          {
            "ClientId": "tweek-openid-mock-client",
            "Description": "Client for implicit flow",
            "AllowedGrantTypes": [
                "implicit"
            ],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": [
                "http://localhost:3000/auth-result/oidc"
            ],
            "AllowedScopes": [
                "openid",
                "profile",
                "email"
            ],
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600
          }
        ]

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
  minio_access_key:
    file: ./minio/access_key
  minio_secret_key:
    file: ./minio/secret_key
