version: '3.4'

services:
  api:
    image: soluto/tweek-api
    build:
      context: ../../
      dockerfile: TweekApiDockerfile

  authoring:
    image: soluto/tweek-authoring
    build: ../../services/authoring

  editor:
    image: soluto/tweek-editor
    build: ../../services/editor
    depends_on: 
      - api
      - authoring
  
  publishing:
    image: soluto/tweek-publishing
    build: ../../services/publishing

