version: '3.4'

services:
  management:
    image: soluto/tweek-management
    build: ../../services/management
    depends_on:
      - api
    environment:
      - VALIDATION_URL=http://api/validation

  api:
    image: soluto/tweek-api
    build:
      context: ../../
      dockerfile: TweekApiDockerfile

  authoring:
    image: soluto/tweek-authoring
    build: ../../services/authoring

  editor:
    image: soluto/tweek-editor
    build: ../../services/editor
    depends_on: 
      - api
      - authoring
  
  publishing:
    image: soluto/tweek-publishing
    depends_on:
      - management

