version: '2'

services:
  tweek.apiservice.netcore:
    image: soluto/tweek-api:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ../../services/api/Tweek.ApiService.NetCore:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null

  tweek-management:
    image: soluto/tweek-management:dev
    expose:
      - "5858"
    ports:
      - "5858:5858"
    entrypoint:
      - node
      - --debug=5858
      - ./server.js
