version: '3.1'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.1.2
    volumes:
      - ..:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Tweek.sln && dotnet publish ./Tweek.sln -c Release -o ./obj/Docker/publish"
