version: '3.1'

services:
  management:
    environment: 
      - GIT_URL=ssh://git@git/tweek/tests

  editor:
    environment: 
      - CONTINUOUS_UPDATER_INTERVAL=500
      - REQUIRE_AUTH=true
      - TWEEK_AUTH_SCHEMES=httpDigest
      - AUTH_DIGEST_CREDENTIALS=user:pwd

  authoring:
    environment: 
      - GIT_URL=ssh://git@git/tweek/tests
      - CONTINUOUS_UPDATER_INTERVAL=500

  api:
    environment:
      - CorsPolicies__Keys__Origins=http://editor:3000,http://testorigin
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - CorsEnabled=true
  
  selenium:
    image: selenium/standalone-chrome:3.8.1
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - gateway:api
      - gateway:authoring

  e2e-ui:
    build: ../../e2e/ui
    container_name: e2e-ui
    links:
      - selenium
      - gateway:api
      - gateway:authoring
    depends_on: 
      - selenium
      - management
      - editor
      - gateway
      - casbin-minio-loader
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000/
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
      - AUTH_DIGEST_CREDENTIALS=user:pwd
    secrets:
      - tweek_ssh_private_key      

  e2e-integration:
    build: ../../e2e/integration
    container_name: e2e-integration
    depends_on:
      - management
      - gateway
      - casbin-minio-loader
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - MANAGEMENT_URL=http://management:3000
      - GATEWAY_URL=http://gateway
      - GIT_PRIVATE_KEY_PATH=/run/secrets/tweek_ssh_private_key
    secrets:
      - tweek_ssh_private_key
    links:
      - gateway:api
      - gateway:authoring
      - gateway:management

  smoke-tests:
    build:
      context: ../../
      dockerfile: TweekApiSmokeTestDockerfile
    container_name: smoke-tests
    depends_on: 
      - management
      - gateway
      - casbin-minio-loader
    environment: 
      - TWEEK_API_URL=http://api/
    links:
      - gateway:api

secrets:
  tweek_ssh_private_key:
    file: ./ssh/tweekgit
