
git-server:
  build: .
  restart: always
  container_name: git-server
  ports:
    - 22
  environment:
    - PUBLIC_KEY_PATH=/git-server/key.pub
  volumes:
    - ../ssh/tweekgit.pub:/git-server/key.pub