version: "2"

networks:
  tweek: 
    driver: bridge

services:
  tweek-management:
    image: soluto/tweek-management
    container_name: tweek-management
    links:
      - tweek-git
    networks:
      - tweek
    volumes:
      - ../GitService/ssh:/keys
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@tweek-git/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/keys/tweekgit.pub
      - GIT_PRIVATE_KEY_PATH=/keys/tweekgit
      - VALIDATION_URL=http://tweek-api/validation

  tweek-git:
    build: ../GitService/BareRepository/.
    container_name: tweek-git
    networks:
      - tweek
    environment:
      - PUBLIC_KEY_PATH=/tweek/key.pub
      - TWEEK_MANAGEMENT_URL=http://tweek-management:3000
    volumes:
      - ../GitService/ssh/tweekgit.pub:/tweek/key.pub

  tweek-api:
    image: soluto/tweek-api
    container_name: tweek-api
    links:
      - tweek-management
    expose:
      - 80
    ports:
      - "1111:80"
    networks:
      - tweek
    environment:
      - RulesBlob.Url=http://tweek-management:3000/ruleset/latest

  tweek-backoffice:
    build: .
    container_name: tweek-backoffice
    ports:
      - "4000:3000"
    networks:
      - tweek
    volumes: 
      - ../GitService/ssh:/keys
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@tweek-git/tweek/repo
      - GIT_PUBLIC_KEY_PATH=/keys/tweekgit.pub
      - GIT_PRIVATE_KEY_PATH=/keys/tweekgit
      - TWEEK_API_HOSTNAME=http://tweek-api
