apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: editor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
      - name: editor
        image: soluto/tweek-editor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: editor
spec:
  selector:
    app: editor
  ports:
    - port: 3000
      targetPort: 3000
