apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tweek
  name: editor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
      - name: editor
        image: soluto/tweek-editor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_GATEWAY_URL
          value: http://192.168.99.100:30099
        volumeMounts:
        - name: tweek-secrets
          mountPath: /run/secrets/tweek-secrets
      volumes:
        - name: tweek-secrets
          secret:
            secretName: tweek-secrets
---
kind: Service
apiVersion: v1
metadata:
  namespace: tweek
  name: editor
spec:
  type: NodePort
  selector:
    app: editor
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004