apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: soluto/tweek-gateway
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 80
        env:
        - name: TWEEKGATEWAY_SECURITY_CORS_ENABLED
          value: "true"
        - name: TWEEKGATEWAY_SECURITY_CORS_MAXAGE
          value: "60"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDORIGINS
          value: "['*']"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDMETHODS
          value: "['GET','POST','PUT','PATCH','DELETE']"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDHEADERS
          value: "['*']"
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOENDPOINT
          value: minio:9000
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOBUCKETNAME
          value: tweek
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOACCESSKEY
          value: AKIAIOSFODNN7EXAMPLE
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECRETKEY
          valueFrom:
            secretKeyRef:
              name: tweek-secrets
              key: minio_secret_key
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECURE
          value: "false"
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOPOLICYOBJECTNAME
          value: policy.csv
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSENDPOINT
          value: nats://nats:4222
        - name: TWEEKGATEWAY_SECURITY_TWEEKSECRETKEY_PATH
          value: /run/secrets/git/tweek_ssh_private_key
        - name: TWEEKGATEWAY_CONFIGFILEPATH
          value: /config/gateway.json
        - name: CONFIGOR_ENV
          value: k8s
        volumeMounts:
          - name: git-keys
            mountPath: /run/secrets/git
          - name: gateway-config
            mountPath: /config
      volumes:
        - name: git-keys
          secret:
            secretName: tweek-secrets
            defaultMode: 0600
        - name: gateway-config
          configMap:
            name: gateway-config
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30099