apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweek-editor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweek-editor
    spec:
      containers:
      - name: tweek-editor
        image: soluto/tweek-editor
        ports:
        - containerPort: 3000
        env:
        - name: GIT_PUBLIC_KEY_PATH
          value: /run/secrets/tweek-git/tweek_ssh_public_key
        - name: GIT_PRIVATE_KEY_PATH
          value: /run/secrets/tweek-git/tweek_ssh_private_key
        - name: GIT_USER
          value: git
        - name: GIT_URL
          value: ssh://git@tweek-git/tweek/repo
        volumeMounts:
        - name: git-keys
          mountPath: /run/secrets/tweek-git
      volumes:
        - name: git-keys
          secret:
            secretName: tweek-git