ci-build:
  image: microsoft/dotnet:1.1.1-sdk
  volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - ./..:/src
    - ./NuGet.Config:/root/.nuget/NuGet/NuGet.Config
  working_dir: /src
  net: "host"
  environment:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
  command: /bin/bash
