version: '2'

networks:
  tweek: 
    driver: bridge

services:
  tweek-git:
      build: ../GitService/BareRepository/.
      container_name: tweek-git
      networks:
        - tweek
      environment:
        - PUBLIC_KEY_PATH=/tweek/key.pub
        - TWEEK_MANAGEMENT_URL=http://tweek-management:3000
      volumes:
        - ../GitService/ssh/tweekgit.pub:/tweek/key.pub
  
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./..:/src
      - ./NuGet.Config:/root/.nuget/NuGet/NuGet.Config
    working_dir: /src
    network_mode: host
    environment:
      - VERSION_SUFFIX=ci-${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    command: /bin/bash

  tweek-management:
      image: soluto/tweek-management
      container_name: tweek-management
      depends_on:
        - tweek-git
      networks:
        - tweek
      volumes:
        - ../GitService/ssh:/keys
      environment:
        - GIT_USER=git
        - GIT_URL=ssh://git@tweek-git/tweek/tests
        - GIT_PUBLIC_KEY_PATH=/keys/tweekgit.pub
        - GIT_PRIVATE_KEY_PATH=/keys/tweekgit
        - VALIDATION_URL=http://tweek-api/validation