version: '2'
services:
  git:
    image: $REPOSITORY_IMAGE
    environment:
      - PUBLIC_KEY_INLINE=c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFERXdpL1RBQ2d3MGV5eEhQMGVpT3pySUo2U1gwT3YwUXE1bm5TQzMvSEx4azRMTkFsNmRlaWVoTEd0VDRUcVFvdzltcGJ3ZzlTSHNhSDhrZWJVVmF6VjVQQnJkblg1UVFXU0xkRDE0TVVnOU03Zm1kcXBYU2xTdGpiQW90TmFmZXp1OTJGd0JJNWUrNk96S3EraVVJK1FTcXNCUzRoQmFEbkFiUWtPNm5HZi9TMUVpaW80NGZYcUovRmxpdnNNTGo4RW0rQWZxTzJTN21mbGN3dndDSzZEQ25DVkpKSWJ5KzU2NjltYWZCUjBtQ283Y05RY3U1S2tXbEM3WW5vWEsveDFScGhQVlcycGYySEV1SWVZWVJFcUV2N21ROGJoM1hjR2gzbE5kVjJqckhGOEk5cUdGU2ZPVjB4NndEUnY5VnBEd0NKQ0dTZ0p4Q0pzNXF0VHZUZEYgeXNoYXlAWXNoYXktUEMK
  
  publishing:
    image: $PUBLISHING_IMAGE
    depends_on:
      - git
      - minio
      - nats
    logging:
      driver: "none"
    environment:
      - GIT_PUBLIC_KEY_INLINE=c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFERXdpL1RBQ2d3MGV5eEhQMGVpT3pySUo2U1gwT3YwUXE1bm5TQzMvSEx4azRMTkFsNmRlaWVoTEd0VDRUcVFvdzltcGJ3ZzlTSHNhSDhrZWJVVmF6VjVQQnJkblg1UVFXU0xkRDE0TVVnOU03Zm1kcXBYU2xTdGpiQW90TmFmZXp1OTJGd0JJNWUrNk96S3EraVVJK1FTcXNCUzRoQmFEbkFiUWtPNm5HZi9TMUVpaW80NGZYcUovRmxpdnNNTGo4RW0rQWZxTzJTN21mbGN3dndDSzZEQ25DVkpKSWJ5KzU2NjltYWZCUjBtQ283Y05RY3U1S2tXbEM3WW5vWEsveDFScGhQVlcycGYySEV1SWVZWVJFcUV2N21ROGJoM1hjR2gzbE5kVjJqckhGOEk5cUdGU2ZPVjB4NndEUnY5VnBEd0NKQ0dTZ0p4Q0pzNXF0VHZUZEYgeXNoYXlAWXNoYXktUEMK
      - GIT_SERVER_PRIVATE_KEY_INLINE=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeE1JdjB3QW9NTkhzc1J6OUhvanM2eUNla2w5RHI5RUt1WjUwZ3QveHk4Wk9DelFKCmVuWG9ub1N4clUrRTZrS01QWnFXOElQVWg3R2gvSkhtMUZXczFlVHdhM1oxK1VFRmtpM1E5ZURGSVBUTzM1bmEKcVYwcFVyWTJ3S0xUV24zczd2ZGhjQVNPWHZ1anN5cXZvbENQa0VxckFVdUlRV2c1d0cwSkR1cHhuLzB0UklvcQpPT0gxNmlmeFpZcjdEQzQvQkp2Z0g2anRrdTVuNVhNTDhBaXVnd3B3bFNTU0c4dnVldXZabW53VWRKZ3FPM0RVCkhMdVNwRnBRdTJKNkZ5djhkVWFZVDFWdHFYOWh4TGlIbUdFUktoTCs1a1BHNGQxM0JvZDVUWFZkbzZ4eGZDUGEKaGhVbnpsZE1lc0EwYi9WYVE4QWlRaGtvQ2NRaWJPYXJVNzAzUlFJREFRQUJBb0lCQVFDWmpOWVh1N0toenVJQgpvcGJpNG9iS1JDMmNHMTVPY2p3RmVlU0JVbFYzNnExelRzdnExdU9QK2d4VExaQ1Q1UlZlNmlyTFRvWm8wemFRClRpaXZJcUY4VjJ0TTRpalZPV29vbHpyUTkvVy9iMjJXMEpIMXhHK0FUaFZTcG45OHluTkNWcXFpNmR0Vnd0b1EKODhvWFNQbVE2TVNsZ1JXM3ZhZjhSTnRoMlpLTkFIOTdZOHBqVk1YL3FMTDFuWjk1YnFvclJJTFJ6ektHSmpxRwplN0VpeFQ0a0JaemxHWUF5a1dVeFFZZzBkdTlnQjc1U1o2MHNwZzVUQlh5a3RXdzVIWG1ZWlMvSHdCOVRKbG1XClRqeVZ0T2VWbGpPRmI4VmdIcE13d3UyTW9yN1ZQQVB3Z0RYdXFGTVd2RnpxVWJIY1VLclcwZ0JITGpYU1BtUzYKMEwxSTNjV0JBb0dCQVBPeHlxSmZ4cnpVQ1BuM3AzbVk2cjZnbHlYYi8rZWFYYTQ2N3NOWThNWnBWZGw1bVFKVgpuOEdRN3FYaklaa2pCU2E5YzZZQThxOFRLVHlJbEcvTDE1OFVSaFRqZldNSC9nandaem1oSmVkL0N6Lzg1Y2V4CmxRbDdsTi9SMjRUYjN3VTE2M21FeW5oR1JXNUt3cWNVNW9FQm1uOS9ZazhoaWJraTZoSTY0QWhsQW9HQkFNNngKcVBabi9uaHY4dSttT2U3Y3pTVjVMc3dmTTNTU3NuZlhnUVJXN3J6a2hrZnJRWjJlWHpFQ21oVk8vdUpWb01iVApoQS9tUXRYRzVuMk9QMndmSk1LVUNiVVZ2ZTJYNUQxU1VGYk03dWVHU3JlWExXdXJzaHdnN1p6VlpxVDYzUEJSCmpUa1FFNHJ1a1ZFSzNNMFVQOUlNVndzYURqMjgrY01RZk5ORmh0VmhBb0dBQ1Q5cStDUjRUendncHhPOTJFQjAKVUEyYURzYTlmRldBVHBkUDdqdld6MEM2RUVtc0E4bXFDVmR0cHYvcWkzd251dU9mbXVJWVU0cC9teHQzdnBKVwp1V08wa1NCYzVzQXI1THp5dmQ0ZXFSMUtHUUNJMjc0aWNMeXUxcHVKSUE2VDlRZXB5dSsrR3poWGRDc0VIZ0VPCkNrRThVckJMMDhMckRncUVKWEwwZzMwQ2dZQm0welVtR0FnZExEd2tBb0xSbEtDdDRzSm9JNkY2ZmJ3eEtGRnoKc2pla1d0OStpY2VqdlBUSU1lNHJhWmdkU3RIbjk3TzhJU1hncWNsaWJ0Q1lYa253VHFzaG5nWlZXM25kRThVSgoyWHVFVEdlQk84RUp6bW1WMnIrNmhPTkNjZFpWNjR3ZzlpRnl2VW9ua2dyVUx4MnN4aHpMVmhQOW5MUjMyUXp3CklhZDVJUUtCZ1FEWHBhU25seGcrbzMyV0FHd0dzQXhxNUNXK3JFcE84UENEbytSZWU2dmNGN25JZi95NHNSUHUKNDFpcFo2WHhZcHdnUkQ3em5aano5QWVWaEc4aUFBQUJORlUxSkZUaVhpZ1BEWi8wOFlFMHRnQ1ZiL0VPV2ZxVAptS0NBTUgrSjJZWUlwb3NLL3dyQmRXQ1RiUHYvYUI3RkVraFFLeGVJTXYxd0trd2tSaU5BQ0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      - GIT_UPSTREAM_URI=ssh://git@git/tweek/tests
      - MINIO__Endpoint=minio:9000
      - MINIO__AccessKey=AKIAIOSFODNN7EXAMPLE
      - MINIO__SecretKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO__Bucket=tweek
      - NATS__Endpoint=nats://nats:4222
      
  api:
    image: $API_IMAGE
    depends_on:
      - minio
      - redis
      - nats
    logging:
      driver: "none"
    environment:
      - Rules__Minio__Endpoint=minio:9000
      - Rules__Minio__AccessKey=AKIAIOSFODNN7EXAMPLE
      - Rules__Minio__SecretKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - Rules__Nats__Endpoint=nats://nats:4222
      - UseAddon__Rules=MinioRules
      - RulesetVersionProvider=NatsVersionProvider
      - PUBLIC_KEY_INLINE=MIIElAIBAzCCBFoGCSqGSIb3DQEHAaCCBEsEggRHMIIEQzCCBD8GCSqGSIb3DQEHBqCCBDAwggQsAgEAMIIEJQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIQLuW21q/z3wCAggAgIID+HlU4K9+e3s0EmVWGpzX+MXQUdKV4Jk2SXsvXGoBoq/P2dpzkV9Uyq7ybjTv6dpesb9eikaRTsL4w6QW/79ScGUZBj9SogQIMfdxmqqjr6sTQExwZMecxbzWziCsWMfKb+kyH4zWmGpTcFYQFjw3o1Btky6hKchBamPEmhMSO9lFFG5JxSLVUj6i8NiQo9xcLYOAtnebNaXM+e3yEuWNBcIGBIwc8qufnxr3lJgQBeHX4z4D+pS0z8vs4sXtJr5/5bc07xPCLl0OkAMBFmux3BiPI96Me1YtUSax0q83JRxM8LHdtncec/f1v7Jx4jlEFY5hx0k9XUjH/TyLY/oLC95NbJg14vZbNxPpOxNeZST7srF1fybGNTgczrfcuKtPLb3O+gaad4b3oDFWuM7yExFx5KjqsrRikt/zCGTrcKHadJ/6eLqhzYDm6nlaFHViQo5E0Yj8SOCApD5lRqlN033fTD0S/vrgyESlRKS6hZl9YC5FCXnKX899CDiRfvMBCMPKs7dxl4LrfJtuIv3jgqp7+X44MSrrRDX6lgJqsYsYNHTcKUSKkp2JzRvbs8J7oa0cOKC96t1KHLcMk7iffx4qqqrSGEKlSzPWi4U4L8ZU8m0vzvddoovr6bQoXBeBOeAyBrzEoNWdQ4HAMRSe0w3fKpV1ygJeK8LdR3q3G2rdLs8obiQ+0I+tJg83+Jdz69nR7ljiygLhVexyFoZgj/kAMKT5rUrocMslSw9n+gzQXxX43Os2bsVok2i0Wt8P+PSsc0RYc8XJgc54tQNt4coeaJRCr+4i/Ga0zjelHY6Z5rDsouu88RPL3oOX1dmrjw/RN3Y7klxckYFAQJMRGDnMW5aM/QeSoAxxmMjlkxbvd2etXI8SqRIEUginvYmnh0fYZ7Vo4o72LVTWS8M4nhmqR1AMxr1BNXk9Uwlp50+Amr4lZHSnl/8HgoFnBYjex57ZjRAoAJ0+ffQXl87Bv31BU1MNi//jlzApCVkCZ5uoVDSBAaSyD/Hwd8uLyeJF1ugDZinfaHjpJaIXEgK+jyju/EhhtKMGeKXnMtKATL/O2Tl/4O8V6UGuk9lrojO9t7wHHbxt1SfpQpvW2aAKzxf9GFSdOob9J1LXnik0LKwWhXHsyYNtFm9WMgacc3xoTs/GkiTJHsyjVcSon8DmET5GMaTVlxGk2lZcgg4Sd6DKTciL2Q8WRybrvSeKcC/njUKw9fylD0dbp6fZ7GrxsvGULHROJfVKNIj05tcciDtXchwOY18OQp/sHRkbymfRufExjRxViu0S8STXMbxd4Cp0FWaaDL6jSvEVbkPdgPk6r7DWgk0Yetai9E1YDYv4jQ8wdlGNH+WXMDEwITAJBgUrDgMCGgUABBS0j+Z1HX5UVJrqbq2mqww5ZHHE9QQIKcY2oy1jhcsCAggA
      - Redis__ConnectionString=redis:6379
      - CorsPolicies__Keys__Origins=http://editor,http://testorigin,http://gateway
      - CorsPolicies__Keys__Methods=GET
      - CorsPolicies__Keys__MaxPreflightAge=60
      - CorsEnabled=true
      - CorsPolicies__Keys__Headers=
      - CorsPolicies__Keys__ExposedHeaders=
      - Context__Validation__ErrorPolicy=throw
      
  authoring:
    image: $AUTHORING_IMAGE
    depends_on:
      - publishing    
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@publishing/tweek/repo
      - GIT_PRIVATE_KEY_INLINE=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeE1JdjB3QW9NTkhzc1J6OUhvanM2eUNla2w5RHI5RUt1WjUwZ3QveHk4Wk9DelFKCmVuWG9ub1N4clUrRTZrS01QWnFXOElQVWg3R2gvSkhtMUZXczFlVHdhM1oxK1VFRmtpM1E5ZURGSVBUTzM1bmEKcVYwcFVyWTJ3S0xUV24zczd2ZGhjQVNPWHZ1anN5cXZvbENQa0VxckFVdUlRV2c1d0cwSkR1cHhuLzB0UklvcQpPT0gxNmlmeFpZcjdEQzQvQkp2Z0g2anRrdTVuNVhNTDhBaXVnd3B3bFNTU0c4dnVldXZabW53VWRKZ3FPM0RVCkhMdVNwRnBRdTJKNkZ5djhkVWFZVDFWdHFYOWh4TGlIbUdFUktoTCs1a1BHNGQxM0JvZDVUWFZkbzZ4eGZDUGEKaGhVbnpsZE1lc0EwYi9WYVE4QWlRaGtvQ2NRaWJPYXJVNzAzUlFJREFRQUJBb0lCQVFDWmpOWVh1N0toenVJQgpvcGJpNG9iS1JDMmNHMTVPY2p3RmVlU0JVbFYzNnExelRzdnExdU9QK2d4VExaQ1Q1UlZlNmlyTFRvWm8wemFRClRpaXZJcUY4VjJ0TTRpalZPV29vbHpyUTkvVy9iMjJXMEpIMXhHK0FUaFZTcG45OHluTkNWcXFpNmR0Vnd0b1EKODhvWFNQbVE2TVNsZ1JXM3ZhZjhSTnRoMlpLTkFIOTdZOHBqVk1YL3FMTDFuWjk1YnFvclJJTFJ6ektHSmpxRwplN0VpeFQ0a0JaemxHWUF5a1dVeFFZZzBkdTlnQjc1U1o2MHNwZzVUQlh5a3RXdzVIWG1ZWlMvSHdCOVRKbG1XClRqeVZ0T2VWbGpPRmI4VmdIcE13d3UyTW9yN1ZQQVB3Z0RYdXFGTVd2RnpxVWJIY1VLclcwZ0JITGpYU1BtUzYKMEwxSTNjV0JBb0dCQVBPeHlxSmZ4cnpVQ1BuM3AzbVk2cjZnbHlYYi8rZWFYYTQ2N3NOWThNWnBWZGw1bVFKVgpuOEdRN3FYaklaa2pCU2E5YzZZQThxOFRLVHlJbEcvTDE1OFVSaFRqZldNSC9nandaem1oSmVkL0N6Lzg1Y2V4CmxRbDdsTi9SMjRUYjN3VTE2M21FeW5oR1JXNUt3cWNVNW9FQm1uOS9ZazhoaWJraTZoSTY0QWhsQW9HQkFNNngKcVBabi9uaHY4dSttT2U3Y3pTVjVMc3dmTTNTU3NuZlhnUVJXN3J6a2hrZnJRWjJlWHpFQ21oVk8vdUpWb01iVApoQS9tUXRYRzVuMk9QMndmSk1LVUNiVVZ2ZTJYNUQxU1VGYk03dWVHU3JlWExXdXJzaHdnN1p6VlpxVDYzUEJSCmpUa1FFNHJ1a1ZFSzNNMFVQOUlNVndzYURqMjgrY01RZk5ORmh0VmhBb0dBQ1Q5cStDUjRUendncHhPOTJFQjAKVUEyYURzYTlmRldBVHBkUDdqdld6MEM2RUVtc0E4bXFDVmR0cHYvcWkzd251dU9mbXVJWVU0cC9teHQzdnBKVwp1V08wa1NCYzVzQXI1THp5dmQ0ZXFSMUtHUUNJMjc0aWNMeXUxcHVKSUE2VDlRZXB5dSsrR3poWGRDc0VIZ0VPCkNrRThVckJMMDhMckRncUVKWEwwZzMwQ2dZQm0welVtR0FnZExEd2tBb0xSbEtDdDRzSm9JNkY2ZmJ3eEtGRnoKc2pla1d0OStpY2VqdlBUSU1lNHJhWmdkU3RIbjk3TzhJU1hncWNsaWJ0Q1lYa253VHFzaG5nWlZXM25kRThVSgoyWHVFVEdlQk84RUp6bW1WMnIrNmhPTkNjZFpWNjR3ZzlpRnl2VW9ua2dyVUx4MnN4aHpMVmhQOW5MUjMyUXp3CklhZDVJUUtCZ1FEWHBhU25seGcrbzMyV0FHd0dzQXhxNUNXK3JFcE84UENEbytSZWU2dmNGN25JZi95NHNSUHUKNDFpcFo2WHhZcHdnUkQ3em5aano5QWVWaEc4aUFBQUJORlUxSkZUaVhpZ1BEWi8wOFlFMHRnQ1ZiL0VPV2ZxVAptS0NBTUgrSjJZWUlwb3NLL3dyQmRXQ1RiUHYvYUI3RkVraFFLeGVJTXYxd0trd2tSaU5BQ0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      - GIT_PUBLIC_KEY_INLINE=c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFERXdpL1RBQ2d3MGV5eEhQMGVpT3pySUo2U1gwT3YwUXE1bm5TQzMvSEx4azRMTkFsNmRlaWVoTEd0VDRUcVFvdzltcGJ3ZzlTSHNhSDhrZWJVVmF6VjVQQnJkblg1UVFXU0xkRDE0TVVnOU03Zm1kcXBYU2xTdGpiQW90TmFmZXp1OTJGd0JJNWUrNk96S3EraVVJK1FTcXNCUzRoQmFEbkFiUWtPNm5HZi9TMUVpaW80NGZYcUovRmxpdnNNTGo4RW0rQWZxTzJTN21mbGN3dndDSzZEQ25DVkpKSWJ5KzU2NjltYWZCUjBtQ283Y05RY3U1S2tXbEM3WW5vWEsveDFScGhQVlcycGYySEV1SWVZWVJFcUV2N21ROGJoM1hjR2gzbE5kVjJqckhGOEk5cUdGU2ZPVjB4NndEUnY5VnBEd0NKQ0dTZ0p4Q0pzNXF0VHZUZEYgeXNoYXlAWXNoYXktUEMK
      
  editor:
    image: $EDITOR_IMAGE
    depends_on:
      - gateway
    logging:
      driver: "none"

  gateway:
    image: $GATEWAY_IMAGE
    depends_on:
      - minio
      - nats
      - api
      - authoring
      - oidc-server-mock    
    environment:
      - TWEEKGATEWAY_SECURITY_CORS_ENABLED=true
      - TWEEKGATEWAY_SECURITY_CORS_MAXAGE=60
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDORIGINS=['*']
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDMETHODS=['GET','POST','PUT','PATCH','DELETE']
      - TWEEKGATEWAY_SECURITY_CORS_ALLOWEDHEADERS=['*']      
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOENDPOINT=minio:9000
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOBUCKETNAME=tweek
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOACCESSKEY=AKIAIOSFODNN7EXAMPLE
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECRETKEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECURE=false
      - TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSENDPOINT=nats://nats:4222
      - TWEEKGATEWAY_SECURITY_TWEEKSECRETKEY_INLINE=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeE1JdjB3QW9NTkhzc1J6OUhvanM2eUNla2w5RHI5RUt1WjUwZ3QveHk4Wk9DelFKCmVuWG9ub1N4clUrRTZrS01QWnFXOElQVWg3R2gvSkhtMUZXczFlVHdhM1oxK1VFRmtpM1E5ZURGSVBUTzM1bmEKcVYwcFVyWTJ3S0xUV24zczd2ZGhjQVNPWHZ1anN5cXZvbENQa0VxckFVdUlRV2c1d0cwSkR1cHhuLzB0UklvcQpPT0gxNmlmeFpZcjdEQzQvQkp2Z0g2anRrdTVuNVhNTDhBaXVnd3B3bFNTU0c4dnVldXZabW53VWRKZ3FPM0RVCkhMdVNwRnBRdTJKNkZ5djhkVWFZVDFWdHFYOWh4TGlIbUdFUktoTCs1a1BHNGQxM0JvZDVUWFZkbzZ4eGZDUGEKaGhVbnpsZE1lc0EwYi9WYVE4QWlRaGtvQ2NRaWJPYXJVNzAzUlFJREFRQUJBb0lCQVFDWmpOWVh1N0toenVJQgpvcGJpNG9iS1JDMmNHMTVPY2p3RmVlU0JVbFYzNnExelRzdnExdU9QK2d4VExaQ1Q1UlZlNmlyTFRvWm8wemFRClRpaXZJcUY4VjJ0TTRpalZPV29vbHpyUTkvVy9iMjJXMEpIMXhHK0FUaFZTcG45OHluTkNWcXFpNmR0Vnd0b1EKODhvWFNQbVE2TVNsZ1JXM3ZhZjhSTnRoMlpLTkFIOTdZOHBqVk1YL3FMTDFuWjk1YnFvclJJTFJ6ektHSmpxRwplN0VpeFQ0a0JaemxHWUF5a1dVeFFZZzBkdTlnQjc1U1o2MHNwZzVUQlh5a3RXdzVIWG1ZWlMvSHdCOVRKbG1XClRqeVZ0T2VWbGpPRmI4VmdIcE13d3UyTW9yN1ZQQVB3Z0RYdXFGTVd2RnpxVWJIY1VLclcwZ0JITGpYU1BtUzYKMEwxSTNjV0JBb0dCQVBPeHlxSmZ4cnpVQ1BuM3AzbVk2cjZnbHlYYi8rZWFYYTQ2N3NOWThNWnBWZGw1bVFKVgpuOEdRN3FYaklaa2pCU2E5YzZZQThxOFRLVHlJbEcvTDE1OFVSaFRqZldNSC9nandaem1oSmVkL0N6Lzg1Y2V4CmxRbDdsTi9SMjRUYjN3VTE2M21FeW5oR1JXNUt3cWNVNW9FQm1uOS9ZazhoaWJraTZoSTY0QWhsQW9HQkFNNngKcVBabi9uaHY4dSttT2U3Y3pTVjVMc3dmTTNTU3NuZlhnUVJXN3J6a2hrZnJRWjJlWHpFQ21oVk8vdUpWb01iVApoQS9tUXRYRzVuMk9QMndmSk1LVUNiVVZ2ZTJYNUQxU1VGYk03dWVHU3JlWExXdXJzaHdnN1p6VlpxVDYzUEJSCmpUa1FFNHJ1a1ZFSzNNMFVQOUlNVndzYURqMjgrY01RZk5ORmh0VmhBb0dBQ1Q5cStDUjRUendncHhPOTJFQjAKVUEyYURzYTlmRldBVHBkUDdqdld6MEM2RUVtc0E4bXFDVmR0cHYvcWkzd251dU9mbXVJWVU0cC9teHQzdnBKVwp1V08wa1NCYzVzQXI1THp5dmQ0ZXFSMUtHUUNJMjc0aWNMeXUxcHVKSUE2VDlRZXB5dSsrR3poWGRDc0VIZ0VPCkNrRThVckJMMDhMckRncUVKWEwwZzMwQ2dZQm0welVtR0FnZExEd2tBb0xSbEtDdDRzSm9JNkY2ZmJ3eEtGRnoKc2pla1d0OStpY2VqdlBUSU1lNHJhWmdkU3RIbjk3TzhJU1hncWNsaWJ0Q1lYa253VHFzaG5nWlZXM25kRThVSgoyWHVFVEdlQk84RUp6bW1WMnIrNmhPTkNjZFpWNjR3ZzlpRnl2VW9ua2dyVUx4MnN4aHpMVmhQOW5MUjMyUXp3CklhZDVJUUtCZ1FEWHBhU25seGcrbzMyV0FHd0dzQXhxNUNXK3JFcE84UENEbytSZWU2dmNGN25JZi95NHNSUHUKNDFpcFo2WHhZcHdnUkQ3em5aano5QWVWaEc4aUFBQUJORlUxSkZUaVhpZ1BEWi8wOFlFMHRnQ1ZiL0VPV2ZxVAptS0NBTUgrSjJZWUlwb3NLL3dyQmRXQ1RiUHYvYUI3RkVraFFLeGVJTXYxd0trd2tSaU5BQ0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      - CONFIGOR_ENV=test
    volumes:
      - /var/lib/docker/volumes/${{CF_VOLUME}}/_data/tweek/deployments/dev/gateway/config:/config

  oidc-server-mock:
    image: soluto/oidc-server-mock
    logging:
      driver: "none"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLIENT_ID=tweek-openid-mock-client
      - REDIRECT_URIS=http://gateway/auth-result/oidc
      - TEST_USER={"SubjectId":"00000000-0000-0000-0000-000000000000","Username":"user","Password":"pwd"}

  redis:
    image: redis:4.0.2-alpine
    expose:
      - "6379"
    logging:
      driver: "none"

  minio:
    image: minio/minio
    logging:
      driver: "none"
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      
  nats:
    image: nats:1.0.4-linux

  selenium:
    image: selenium/standalone-chrome:3.8.1
    logging:
      driver: "none"
    links:
      - gateway:api
      - gateway:authoring