version: '2.1'
services:
  keys:
    build: ../deployments/dev/ssh
    
  git:
    build: ../services/git-service/BareRepository
    ports: 
      - "5001:22"
  
  management:
    build: ../services/management
    logging:
      driver: "json-file"
    ports:
      - "5002:3000"

  api:
    build:
      context: ../
      dockerfile: TweekApiDockerfile
    logging:
      driver: "json-file"
    ports:
      - "5003:80"
      
  authoring:
    build: ../services/authoring
    logging:
      driver: "json-file"
    ports:
      - "5005:3000"
      
  editor:
    build: ../services/editor
    logging:
      driver: "json-file"
    ports:
      - "5004:3000"

  zap-smoke:
    build: ../deployments/dev/zap
    logging:
      driver: "json-file"

  zap-e2e:
    build: ../deployments/dev/zap
    logging:
      driver: "json-file"

  smoke-tests:
    build:
      context: ../
      dockerfile: TweekApiSmokeTestDockerfile
    depends_on: 
      - api
      - management
      - zap-smoke
    environment: 
      - TWEEK_API_URL=http://api/
      - PROXY_URL=http://zap-smoke:8090

  e2e-ui:
    build: ../e2e/ui
    volumes_from:
      - keys
    depends_on: 
      - selenium
      - editor
      - authoring
      - api
      - management
      - zap-e2e
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit
      - PROXY_URL=http://zap-e2e:8090

  e2e-integration:
    build: ../e2e/integration
    volumes_from:
      - keys
    depends_on: 
      - authoring
      - api
      - management
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - MANAGEMENT_URL=http://tweek-management:3000
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit
