on: 
  push:
    paths:
    - 'addons/**'
jobs:
  build-authoring-gateway:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1 
    services:
      redis:
        image: redis:alpine
    steps:
      - uses: actions/checkout@v2
      - name: Build integration tests nuget
        run: |
          mkdir -p /nugets
          export Version=0.2.$GITHUB_RUN_NUMBER
          cd addons/Context/Tweek.Drivers.ContextIntegrationTests/ && \
          dotnet restore && \
          dotnet build -c release -o /nugets
      - name: Build redis driver nuget
        run: |
          mkdir -p /nugets
          export Version=0.1.$GITHUB_RUN_NUMBER
          cd addons/Context/Tweek.Drivers.Context.Redis/ && \
          dotnet restore && \
          dotnet build -c release -o /nugets
      - name: Test redis driver
        run: |
          mkdir -p /nugets
          export Version=0.1.$GITHUB_RUN_NUMBER
          cd addons/Context/Tweek.Drivers.Context.Redis.IntegrationTests/ && \
          dotnet restore && \
          REDIS_TEST_CONNECTION="redis:6379" dotnet test