on: 
  push:
    paths-ignore:
    - 'docs/**'
    - README.md
jobs:
  build-editor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker DH
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
      - name: Login Docker Github
        env: 
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login --username $GITHUB_ACTOR --password-stdin docker.pkg.github.com
      - name: build
        run: cd services/editor && docker buildx build . --cache-from="type=registry,ref=soluto/tweek-editor:build-cache" --cache-to=type="registry,ref=soluto/tweek-editor:build-cache,mode=max" --output="type=image,name=docker.pkg.github.com/soluto/tweek/editor:ref-${GITHUB_SHA},push=true"
      