on: 
  push:
    paths-ignore:
    - 'docs/**'
    - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cd deployments/dev && docker buildx bake -f docker-compose.yml --load