on: 
  push:
    paths-ignore:
    - 'docs/**'
    - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
      - name: build
        run: cd .github/workflows && docker buildx create --use && docker buildx bake --load
      - name: test
        run: yarn test:full-env
