name: Main

on:
  pull_request:
    branches:
      - master
  push:
    paths-ignore:
    - 'docs/**'
    - README.md
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        env:
          USER: ${{ secrets.DOCKER_USER }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo $USER >> secrets.txt
          echo $TOKEN >> secrets.txt
      - name: tmate
        uses: mxschmitt/action-tmate@v3
